### PR TITLE
Nest fan control

### PR DESCRIPTION
**Pull request by pedroserano**
Hi KraigM,

Before I started adding home/away status, I thought I would send the fan control code I created over to you for review. It is currently not working, so any help is greatly appreciated.

-Peter

PS, this is the error I consistently get:

		/usr/local/lib/node_modules/homebridge-nest/index.js:145
				.on('get', function(callback) {
				^
		TypeError: Cannot read property 'on' of undefined
			at new NestThermostatAccessory (/usr/local/lib/node_modules/homebridge-nest/index.js:145:9)
			at /usr/local/lib/node_modules/homebridge-nest/index.js:51:49
			at /usr/local/lib/node_modules/homebridge-nest/node_modules/unofficial-nest-api/index.js:232:17
			at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/node_modules/unofficial-nest-api/index.js:214:25)
			at IncomingMessage.emit (events.js:129:20)
			at _stream_readable.js:908:16
			at process._tickCallback (node.js:355:11)

### CODE REVIEW

**Comment by KraigM** [comment]
Is it not reading or updating I assume?  If so, it is probably because the data for fan is in device instead of currentData.  Humidity was like that. I already setup the update system to watch for and auto update when data from device and/or currentData changes.

**Comment by pedroserano** [comment]
Good question, it is not reading or updating, it looks like it crashes right after it tries to fetch data for the first time. I tried this.device.fanMode for the getCurrentFanMode function, but same error.

	Loaded plugin: homebridge-nest
	Registering platform 'homebridge-nest.Nest'
	---
	Loaded config.json with 0 accessories and 1 platforms.
	---
	Loading 1 platforms...
	[Nest] Initializing Nest platform...
	[Nest] Fetching Nest devices.
	/usr/local/lib/node_modules/homebridge-nest/index.js:145
			.on('get', function(callback) {
			^

**Comment by KraigM** [comment]
The problem is Characteristic.CurrentFanMode doesn't exist.  Did you find documentation that HomeKit has CurrentFanMode?

**Comment by pedroserano** [comment]
Bah! That's a really good reason, and that explains a lot - I was really confused how those variables were defined. So it sounds like HomeKit defines them. Ok, well it was nice to try.

**Comment by KraigM** [comment]
Well if you can find documentation of HomeKit defining them, then we prob could figure it out.  Another option might be to treat nest as both a thermostat and a fan (add the fan service as well as the thermostat service)

**Comment by matt-element** [comment]
Any new information on this? How could we add the fan service? I would really like to be able to get this working.

**Pull request closed without merging**
