### PR TITLE
Use Fahrenheit versions of Nest API to more accurately set and get temperatures (without rounding to nearest 0.5 Celsius)

### PR DESCRIPTION
**Pull request by bheung**
Switched to using Fahrenheit versions of Nest API (target_temperature_f, etc) to get around rounding to the nearest 0.5 C.

### CODE REVIEW

**Comment by bheung** [comment]
The logging is still done in Celsius and shows some converted Fahrenheit temperatures that are not rounded. Tested on a Heat only system and did not exercise the Cooling code paths.

**Comment by KraigM** [comment]
First off AWESOME JOB.  Did not even think about doing that.

I did make a few notes above. Feel free to state what you disagree with.  I just want to make sure we keep the code clean, so we don't run into issues in the future.

**Comment by bheung** [comment]
Still some issues with logging where we switch between F and C without showing any units.

**Comment by KraigM** [comment]
Does that make sense?

**Comment by KraigM** [comment]
Sorry I missed that you had pushed a new commit.  I made one minor adjustment, a couple minor syntax fixes, and with your new changes I restructured the setTargetTemperature method.

Thanks again for the PR.  This enhancement makes it so much smoother to change the temp in Fahrenheit.

Release Note: Has been merged into develop and will be included in next major release

**Pull request merged**
